#!/bin/bash

docker build --build-arg AZURE_CLIENT_ID=${AZURE_CLIENT_ID} --build-arg AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} --build-arg AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} --build-arg AZURE_TENANT_ID=${AZURE_TENANT_ID} .
