name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
        include:
          - python-version: 3.6
            os: ubuntu-latest
            tox-target: py36
          - python-version: 3.7
            os: ubuntu-latest
            tox-target: py37
          - python-version: 3.8
            os: ubuntu-latest
            tox-target: py38

          - python-version: 3.6
            os: windows-latest
            tox-target: py36
          - python-version: 3.7
            os: windows-latest
            tox-target: py37
          - python-version: 3.8
            os: windows-latest
            tox-target: py38

          - python-version: 3.6
            os: macos-latest
            tox-target: py36
          - python-version: 3.7
            tox-target: py37
            os: macos-latest
          - python-version: 3.8
            tox-target: py38
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .tox/${{ matrix.tox-target }}
          key: venv2-${{ runner.os }}-${{ matrix.tox-target  }}-${{ hashFiles('**/setup.py') }}

      - name: Install Test Runner
        run: |
          python -m pip install pip
          pip install tox codecov

      - name: Install Deps test
        run: |
          tox -e ${{ matrix.tox-target }} --notest

      - name: test
        run : |
          ls -l .tox/py36/lib/python3.6/site-packages/

      - name: test
        run : |
          cat .tox/py36/lib/python3.6/site-packages/c7n-mailer.egg-link

      - name: test
        run : |
          ls /home/runner/work/cloud-custodian/cloud-custodian/tools/c7n_mailer

#
#      - name: Test
#        run: |
#          tox -e ${{ matrix.tox-target }}
